import Head from "next/head";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={``}>
        <h1 className={``}>Get Search Console Data</h1>

        <p className={``}>Getting Data</p>
      </main>
    </div>
  );
}

export async function getServerSideProps(context) {
  let body = JSON.stringify({});

  let res = fetch(
    `${process.env.NEXT_PUBLIC_API}/api/get-search-console-data`,
    {
      method: "POST", // or 'PUT'
      headers: {},
      body: body,
    }
  );

  let resolvedRes = await res;

  return {
    props: {
      data: null,
    },
  };
}
